version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0   # Default is 1000, we use 0 to run as root
      - PGID=0
      - TZ=Atlantic/Canary
    volumes:
      - /home/nick/config/duplicati:/config
        # - /path/to/backups:/backups  -- This line is necessary for backing up onto an external drive
      - /home/nick/config:/source
      - /data:/data
    ports:
      - 8200:8200
    restart: unless-stopped
  minecraft:
    image: openjdk:17
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - ./minecraft/aqm2_server_files:/data
    working_dir: /data
    command: ./startserver.sh
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Atlantic/Canary
      - FILE__PASSWORD=/home/nick/config/code-server/.pass
        # - HASHED_PASSWORD= #optional
        # - SUDO_PASSWORD=password #optional
        # - SUDO_PASSWORD_HASH= #optional
        # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/data
    volumes:
      - /home/nick/config/code-server:/config
      - /home/nick/config:/root-config
      - /data/code-server:/data
    ports:
      - 8443:8443
    restart: unless-stopped

